### ISSUE TITLE
rt-n56u 项目无法构建

### ISSUE THREAD

**Issue by XFZAIMFQ** [ZenZRyan/minieap-openwrt#4]
打扰了.
请问一下大佬为什么把minieap删库了.
另外一个仓库无法发issue所以在这边发了.

**Comment by AutoCONFIG** [comment]
感谢来信。
我这里的是修改后的专用版本，只有在我这里测试正常，因适用范围不大，所以改为私有库。
这个bug会在两天内提交修复，感谢耐心等待。

**Comment by XFZAIMFQ** [comment]
> 感谢来信。 我这里的是修改后的专用版本，只有在我这里测试正常，因适用范围不大，所以改为私有库。 这个bug会在两天内提交修复，感谢耐心等待。

好的明白了,谢谢大佬的回复.
